import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";

const inter = Poppins({
  weight: ["100", "200", "500"],
  subsets: ["latin"]  // Añade los subconjuntos que necesitas
});

export const metadata: Metadata = {
  title: "E commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
