import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import NavBar from "@/components/NavBar";

const inter = Poppins({
  weight: ["100", "200", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SideNav/> */}
        <div className="pt-10">
          {children}
          <NavBar />
        </div>
      </body>
    </html>
  );
}
